### ISSUE TITLE
Missing vectorClass

### ISSUE THREAD

**Issue by yourwifeandkids** [bresheske/OpenMario#7]
Hey there, I'm a university CS student looking to pick up C#, and this project looks like a great way to do it. Love how well-organized and well-commented the code is. But when I cloned the repo and opened the solution in VS, I noticed that vectorClass is missing, and causes errors in all other classes where it's a dependency. Could you let me know where I might be able to find vectorClass? Thanks.

**Comment by bresheske** [comment]
Thanks!
Just restore the nuget packages and you should be good to go.

**Comment by yourwifeandkids** [comment]
Ah I see, I'm new to NuGet. That seems to have worked, I was just able to build the solution successfully. Nonetheless, I'm still not clear on where VectorClass is... I'd love to be able to see the code in VectorClass, too, but VS gives me an error when I try to use F12 to navigate to its definition. Thanks for your help!

**Comment by bresheske** [comment]
It's a very simple Vector class, I don't think there's anything special.  You might be able to find the source online by googling the nuget package.  You won't be able to view it in VS as you're referencing a DLL and not a block of source code.  

Glad you got things figured out, let me know if you have any other questions.

**Comment by yourwifeandkids** [comment]
Gotcha. That's a good starting point, I'll try to find some info on Google. Thanks again!
