### ISSUE TITLE
Is this project still active

### ISSUE THREAD

**Issue by edosssa** [bresheske/OpenMario#8]
Hi, i was just wondering if this project is still under development. i'm a 16 year old self taught programmer and was thinking of open source projects to contribute to and this just caught my eye.

**Comment by bresheske** [comment]
Hey @king-kay.  This project is not really developed at this time, but I still look back at it as being written in a pretty up-to-date manner.  There's only a few spots that need re-architecture, and the rest of the code is written pretty cleanly.  If you're looking to learn, I encourage you to check it out.
